package by.kochergin.app.domain;
// Generated 24.04.2016 10:10:15 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientstatus generated by hbm2java
 */
@Entity
@Table(name="clientstatus"
    ,catalog="mydb"
)
public class Clientstatus  implements java.io.Serializable {


     private Integer id;
     private String name;
     private long discountPercent;
     private Set<Parent> parents = new HashSet<Parent>(0);

    public Clientstatus() {
    }

	
    public Clientstatus(String name, long discountPercent) {
        this.name = name;
        this.discountPercent = discountPercent;
    }
    public Clientstatus(String name, long discountPercent, Set<Parent> parents) {
       this.name = name;
       this.discountPercent = discountPercent;
       this.parents = parents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="discountPercent", nullable=false, precision=10, scale=0)
    public long getDiscountPercent() {
        return this.discountPercent;
    }
    
    public void setDiscountPercent(long discountPercent) {
        this.discountPercent = discountPercent;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="clientstatus")
    public Set<Parent> getParents() {
        return this.parents;
    }
    
    public void setParents(Set<Parent> parents) {
        this.parents = parents;
    }




}


