package by.kochergin.app.domain;
// Generated 24.04.2016 10:10:15 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Discountcard generated by hbm2java
 */
@Entity
@Table(name="discountcard"
    ,catalog="mydb"
)
public class Discountcard  implements java.io.Serializable {


     private int id;
     private Parent parent;
     private String number;
     private Integer balance;

    public Discountcard() {
    }

	
    public Discountcard(int id, Parent parent) {
        this.id = id;
        this.parent = parent;
    }
    public Discountcard(int id, Parent parent, String number, Integer balance) {
       this.id = id;
       this.parent = parent;
       this.number = number;
       this.balance = balance;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Parent_id", nullable=false)
    public Parent getParent() {
        return this.parent;
    }
    
    public void setParent(Parent parent) {
        this.parent = parent;
    }
    
    @Column(name="number", length=45)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    
    @Column(name="balance")
    public Integer getBalance() {
        return this.balance;
    }
    
    public void setBalance(Integer balance) {
        this.balance = balance;
    }




}


