package by.kochergin.app.domain;
// Generated 24.04.2016 10:10:15 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Parent generated by hbm2java
 */
@Entity
@Table(name = "parent", catalog = "mydb")
public class Parent implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "client_status_id", nullable = true)
	private Clientstatus clientstatus;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_id", nullable = false)
	private User user;
	@Column(name = "firstname", nullable = false)
	private String firstname;
	@Column(name = "patronymic", length = 45)
	private String patronymic;
	@Column(name = "lastname", nullable = false, length = 120)
	private String lastname;
	@Column(name = "address")
	private String address;
	@Column(name = "phone", length = 45)
	private String phone;
	@Column(name = "mphone", length = 45)
	private String mphone;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "parent")
	@JsonIgnore
	private Set<Child> childs = new HashSet<Child>(0);
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "parent")
	@JsonIgnore
	private Set<Discountcard> discountcards = new HashSet<Discountcard>(0);

	public Parent() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Clientstatus getClientstatus() {
		return this.clientstatus;
	}

	public void setClientstatus(Clientstatus clientstatus) {
		this.clientstatus = clientstatus;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getPatronymic() {
		return this.patronymic;
	}

	public void setPatronymic(String patronymic) {
		this.patronymic = patronymic;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMphone() {
		return this.mphone;
	}

	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

	public Set<Child> getChilds() {
		return this.childs;
	}

	public void setChilds(Set<Child> childs) {
		this.childs = childs;
	}

	public Set<Discountcard> getDiscountcards() {
		return this.discountcards;
	}

	public void setDiscountcards(Set<Discountcard> discountcards) {
		this.discountcards = discountcards;
	}

}
