package by.kochergin.app.domain;
// Generated 24.04.2016 10:10:15 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="mydb"
)
public class Payment  implements java.io.Serializable {


     private int id;
     private Course course;
     private Child child;
     private Date date;
     private long amount;

    public Payment() {
    }

    public Payment(int id, Course course, Child child, Date date, long amount) {
       this.id = id;
       this.course = course;
       this.child = child;
       this.date = date;
       this.amount = amount;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Child_id", nullable=false)
    public Child getChild() {
        return this.child;
    }
    
    public void setChild(Child child) {
        this.child = child;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="amount", nullable=false, precision=10, scale=0)
    public long getAmount() {
        return this.amount;
    }
    
    public void setAmount(long amount) {
        this.amount = amount;
    }




}


