package by.kochergin.app.domain;
// Generated 24.04.2016 10:10:15 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trainer generated by hbm2java
 */
@Entity
@Table(name="trainer"
    ,catalog="mydb"
)
public class Trainer  implements java.io.Serializable {


     private int id;
     private User user;
     private String firstname;
     private String patronomic;
     private String lastname;
     private Set<Course> courses = new HashSet<Course>(0);

    public Trainer() {
    }

	
    public Trainer(int id, User user, String firstname, String patronomic, String lastname) {
        this.id = id;
        this.user = user;
        this.firstname = firstname;
        this.patronomic = patronomic;
        this.lastname = lastname;
    }
    public Trainer(int id, User user, String firstname, String patronomic, String lastname, Set<Course> courses) {
       this.id = id;
       this.user = user;
       this.firstname = firstname;
       this.patronomic = patronomic;
       this.lastname = lastname;
       this.courses = courses;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    @Column(name="firstname", nullable=false, length=45)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    
    @Column(name="patronomic", nullable=false, length=45)
    public String getPatronomic() {
        return this.patronomic;
    }
    
    public void setPatronomic(String patronomic) {
        this.patronomic = patronomic;
    }
    
    @Column(name="lastname", nullable=false, length=45)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="trainer")
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }




}


